baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'iut-lens'
paginate = 6


[[menu.main]]
    name = "projet"
    url = "/projet"
[[menu.main]]
    name = "Blog"
    url = "/blog"
[[menu.main]]
    name = "Categories"
    url = "/Categories"

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/VotreCompteGithub"
    pre = "<i class='fab fa-github'></i>"
[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/VotreCompteTwitter"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
    name = "projet"
    url = "/projet"

[params]
    author = "Axel Poteau"
    authorImage = "/image/mon_avatar.png"
    images = "/image/dev.jpg"

